### ISSUE TITLE
Too long vector?

### ISSUE THREAD

**Issue by xtianfall** [asardaes/dtwclust#12]
Hi, i'm trying to use **tsclust** function over my database (496306 rows and 12 cols) and i get the following error:

`mvc <- tsclust(data3[,15:26], k = nclust, distance = "dtw_basic", seed = 390,centroid="pam") `
I've also try with GAK

`Error in .Call("pairs", n, lower, PACKAGE = "dtwclust") : `
` no se puede asignar un vector de longitud 1506013458`

I don't know if it is because a limitation in R, in the package or in mi computer.

I'll be very glad if you could do someting ;)

**Comment by asardaes** [comment]
Hello. Given your data, you have 496,306 time series with 12 data-points each, so with PAM, it would have to allocate a `496306 x 496306` matrix, which is almost 1TB of data, I believe. I doubt your computer has so much RAM, so it probably can't handle that =P.

Try passing `control = partitional_control(pam.precompute = FALSE)` to `tsclust`. It will be slower, but it wouldn't have to calculate the whole matrix at once.

**Comment by xtianfall** [comment]
Thanks, I'm running with that change and with only 1.000 rows.

I'll keep you informed ;)

**Comment by xtianfall** [comment]
Finally, I make some tests with all distancies and centroids and the best time/dist is with GAK distance an MEAN centroid, so i'll use this for the clustering ;)

**Comment by asardaes** [comment]
Out of curiosity, what running times are you seeing for GAK/mean with 10,000 series? And if you were able to apply it to the whole 496k series, how long did it take?

**Comment by xtianfall** [comment]
I did not remember the time for 10.000 series, and i think that i not compute with that number....
For the 496k was almost 5h.
I've all the information in the work, so on Monday I'll post all my test if you want ;)

**Comment by xtianfall** [comment]
I've done several test, all of them with 6 clusters, I start with GAK distance becouse it gives good results in other test and also theoretically.

```
100 TS, GAK, Shape/Mean/DBA/PAM:
#                  Tiempo      D max      D min    D media
#mvc1006gakshape   1.39 0.06257569 0.01344741 0.03310014
#mvc1006gakmean    0.78 0.03442657 0.01422754 0.02355876
#mvc1006gakdba    14.15 0.05117832 0.02123898 0.03788534
#mvc1006gakpam     0.55 0.04070498 0.01530025 0.02346858
```

```
1000 TS with the same:
#                  Tiempo      D max      D min    D media
#mvc10006gakshape   8.04 0.07965405 0.01637909 0.04079121
#mvc10006gakmean    8.10 0.03812282 0.02169165 0.02962138
#mvc10006gakdba   376.61 0.04670653 0.02614163 0.03407063
#mvc10006gakpam    21.34 0.03132280 0.01555128 0.02347230
```

At this moment I reject DBA centroid because it is very slow and it have no such good average distance.

```
5000 TS:
#                  Tiempo      D max      D min    D media
#mvc50006gakshape 129.87 0.04201452 0.01712892 0.03233005
#mvc50006gakmean   44.07 0.03857510 0.01904716 0.02931135
#mvc50006gakpam     1600 0.03583900 0.01365500 0.02345700
#mvc50006gakmedian84.63  0.03507829  0.01947231  0.02941637
```

Here i also reject pam (so very slow) and shape (slower than mean and with more average distance). And comparing mean and median the best option is mean (very quick and the distance is almos similar).

Now I repeat the test with mean as centroid and I change the distances:
```
#                  Tiempo      D max      D min    D media
#mvc50006mdtw      1099.16 7.31921545 6.13278137 6.81277061
#mvc50006mdtw2     1162.92 2.29309526 1.85540841 2.09266019
#mvc50006mdtwbasic   68.06 7.31921545 6.13278137 6.81277061
#mvc50006mdtwlb     277.44 8.29965231 6.04156029 6.99271788
#mvc50006mlbk        83.66 3.37910620 0.00000000 2.22578217
#mvc50006mlbi       178.42 2.99988020 0.22972892 2.25942524
#mvc50006mgak       114.59 0.04160547 0.01919481 0.03130094 #converge
```

In this comparation I also compare with the plots, and lbi/lbk give very poor results and also (as same as the rest) give a very high distance without of convergence.

So finally i choose GAK-Mean pair to do the clustering.

Doing the polynomial regresión (of order 2) with the data (100:0.78; 1000:8.10; 5000:44.07; 496306:17554.79), i get the following polynomial:
f(x) = (5.395647e-08)*x**2 + (8.592564e-03)*x + (-2.893500e-01)

I hope this is what you'r asking, if you want more information please ask me ;)

**Comment by asardaes** [comment]
Thanks for the info, I was just curious about your running times, it looks interesting.

I find it weird that GAK + PAM was so slow in comparison to the other centroids. Were you using `pam.precompute=FALSE`? If not, it might be worth trying, since the ratio between dataset size and number of clusters is so big (5000 -> 6), it might be considerably faster to prevent the precomputation.

You might also want to consider using CVIs to evaluate, instead of using only average distances, but that's up to you.

**Comment by xtianfall** [comment]
I think that i use pam.precompute=False because my idea was to apply to al series and it was imposible precomputing the matrix.

I read about CVIs but i dont know really how to apply them :S
