### ISSUE TITLE
Calculate distmat in parallel using tsclustFamily with a lot of data

### ISSUE THREAD

**Issue by xtianfall** [asardaes/dtwclust#15]
Hello, now I'm trying to calculate the distance matrix but i dont get a matriz when i do this:
```
fam <- new("tsclustFamily", dist = "dtw",preproc=zscore,control=partitional_control(symmetric=FALSE))
fam@dist(muestra[1:10,])
```
I get this: 
> Error in attr(d, "dimnames") <- dim_names : 
>   length of 'dimnames' [1] not equal to array extent

If i change the second line for this `fam@dist(muestra[1:10,],pairwise=TRUE)`
I get:  
> [1] 0 0 0 0 0 0 0 0 0 0

I know that I can use `proxy::dist(muestra[1:100,], method = "dtw")` but it's not valid por paralelization, and the 10 is just for test, it'd 10k. 

The data estructure is the following:
```
head(muestra)
         X00000001        X00000002        X00000003        X00000004        X00000005        X00000006        X00000007
1              546              335              397                0              350              192                0
2             9482            11608             4692             2244             2114             5753             8482
3             4059             3500             4233             6023             3772             3936             4638
4             7474             4193             4122             7488             4768             4300             5302
5                0                2                0                2                0                9                0
```
```
> dim(muestra);class(muestra)
[1] 10000    90
[1] "data.table" "data.frame"
```
Thanks ;)

PD: Using v 4.0.1

**Comment by xtianfall** [comment]
UPDATE:
with:
```
fam <- new("tsclustFamily", dist = "dtw",preproc=zscore, control = partitional_control(symmetric = TRUE))
fam@dist(muestra[1:10,])
```

> X00000001         X00000002         X00000003         X00000004         X00000005      X00000006         
> X00000001                  0.00000       3512.37242      41876.15576      19131.83143       8259.52033       4457.13495
> X00000002                3512.37242          0.00000      14145.02156         33.45146      16223.00903      39107.93590
> X00000003               41876.15576      14145.02156          0.00000      33209.26702       1088.12040      16557.76618
> ...
> Warning messages:
> 1: In D[upper.tri(D)] <- d :
>   number of items to replace is not a multiple of replacement length
> 2: In D[upper.tri(D)] <- d :
>   number of items to replace is not a multiple of replacement length


but with:
```
fam <- new("tsclustFamily", dist = "gak",preproc=zscore, control = partitional_control(symmetric = TRUE))
fam@dist(muestra[1:10,],sigma=sigmamed)
```

Everything is OK

**Comment by asardaes** [comment]
It seems I forgot to coerce data to a list within the distance function, since `tsclust` does it before calling the family's functions.

For now, change your data to a list before calling the family. You can do this yourself, or use the unexported function I use internally:

```r
series <- dtwclust:::any2list(muestra[1:10,])
fam@dist(series)
```

I think that should be enough to make it work.

**Comment by xtianfall** [comment]
Ok thanks, ill try when it finish with the GAK matrix ;)

**Comment by xtianfall** [comment]
I've try with a small number and it works, tomorrow i'll do with the 10k. Thanks ;)

**Comment by xtianfall** [comment]
It's a weird thing.... I try with
```
fam <- new("tsclustFamily", dist = "dtw",preproc=zscore, control = partitional_control(symmetric = TRUE))
series <- dtwclust:::any2list(muestra[1:nnn,])
matriz10kdtw=fam@dist(series)
```
And for nnn=10,100,1000 everything is OK, but for 10.000 it crash...

I'm trying now with `dtw_basic` and if this crash i'll do with `dtw_lb`.

It is not memory problem, i have 140gb of ram and R doesn't raise me a error of type `cannot allocate vector of size [...]`

I'll keep you informed ;)

**Comment by asardaes** [comment]
Will it simply crash without any error? That would be weird indeed, that it fails with fewer series.

Also, I see that `muestra` is a `data.table`. I am not too familiar with data tables, but I think their indexing doesn't work the same as data frames, i.e. `muestra[1, ]` doesn't return a vector. If that's the case, `any2list` won't work, and you'd have to change `muestra` to a matrix or do the list conversion yourself in a way that is appropriate for data tables.

**Comment by xtianfall** [comment]
With `dtw_basic ` crashes again...
I'd change `muestra` to data.frame using `muestra=as.data.frame(muestra)`, and it works well with nnn=100
I'm executing now for 10.000.

It's very weird anyway... It's possible to see some trace? Like "Executing for 1 of 1000", or every 100?

**Comment by asardaes** [comment]
Right now there's no tracing within the distance functions, and I would only be able to add it for my distances, so using `dtw::dtw` or distances from other packages would not apply.

A sudden crash might indicate there was some memory corruption, but it still doesn't make sense that it works for more series, and taking a subset fails.

**Comment by xtianfall** [comment]
Again it crash... (with `dtw_basic`). I'm trying now with `dtw_lb (window.size = 15L)`.
The error i get is just this, without any error in command line:
![errordtw](https://user-images.githubusercontent.com/26542233/27530166-c0990a9c-5a57-11e7-8393-49858f466df7.PNG)

Can i compute this matrix in other way? (ussing paralization)

**Comment by asardaes** [comment]
The fact that it fails for both `dtw::dtw` and the distances in `dtwclust` makes me think it might be a problem in `proxy`, but it's really hard to tell based on such an error.

If you like, try calling the function directly: `dtwclust:::dtw_basic_proxy(...)`. This is called by `proxy` in the end, and the parallelization step is contained therein.

**Comment by xtianfall** [comment]
UPDATE:
With 
```
fam <- new("tsclustFamily", dist = "dtw_lb",preproc=zscore, control = partitional_control(symmetric = TRUE))
series <- dtwclust:::any2list(muestra)
matriz10kdtw=fam@dist(series,window.size = 15L)
```
It works :D

But it's very strange that it fails with the others :S

**Comment by asardaes** [comment]
If you have time, you can also try calculating the distance matrix with `dtw::dtw` sequentially. If you can, call `proxy::dist` directly (`proxy::dist(series, method = "dtw", ...)`) and also `fam@dist` without a parallel backend (if possible, more than once, to be sure it's not random), and see if one fails but the other one doesn't.

**Comment by asardaes** [comment]
Another test that might help he figure out where the problem is:

```r
fam <- new("tsclustFamily", dist = "dtw", preproc=zscore, control = partitional_control(symmetric = FALSE))
series <- dtwclust:::any2list(muestra[1:nnn,])
matriz10kdtw=fam@dist(series, ...)

fam <- new("tsclustFamily", dist = "dtw",preproc=zscore, control = partitional_control(symmetric = TRUE))
series <- dtwclust:::any2list(muestra[1:nnn,])
matriz10kdtw_basic=fam@dist(series, series, ...)
```

You can do it in parallel if you want, just notice that I set `symmetric = FALSE` for dtw and I call `fam@dist` with two arguments for dtw_basic

**Comment by xtianfall** [comment]
I'll finish with some test and try your code
(in the second you've also use dtw, no dtw_basic)

**Comment by asardaes** [comment]
I edited it, the second one should be dtw_basic indeed.

**Comment by xtianfall** [comment]
I execute for 1k and look good, but the time for `symmetric=FALSE` is rather larger.

```
> nnn=1000
> fam <- new("tsclustFamily", dist = "dtw", preproc=zscore, control = partitional_control(symmetric = FALSE))
> series <- dtwclust:::any2list(muestra[1:nnn,])
> matriz1kdtw=fam@dist(series)
> fam <- new("tsclustFamily", dist = "dtw_basic",preproc=zscore, control = partitional_control(symmetric = TRUE))
> series <- dtwclust:::any2list(muestra[1:nnn,])
> matriz1kdtw_basic=fam@dist(series, series)
> max(abs(matriz1kdtw - matriz1kdtw_basic))
[1] 0
```

I'm executing for nnn=10k but dtw it's been running for 1h... I'll keep you informed ;)

**Comment by asardaes** [comment]
Out of curiosity, why are you comparing dtw and dtw_basic?

If those don't fail, then the problem may be related to the way I calculate half the distance matrix. If you can, try the following:

```r
fam <- new("tsclustFamily", dist = "dtw", preproc=zscore, control = partitional_control(symmetric = TRUE))
debugonce(fam@dist)
matriz10kdtw=fam@dist(series, ...)
```

Then do a step-by-step execution (with F10 if I remember correctly) and see at which point it fails. Maybe when [calculating the amount of pairs](https://github.com/asardaes/dtwclust/blob/master/R/ddist2.R#L71) or [executing the foreach loop](https://github.com/asardaes/dtwclust/blob/master/R/ddist2.R#L74).

**Comment by xtianfall** [comment]
Just checking, i know that is not necessasy simmetryc.

It continue executing, I'll save the code for execute when it finish ;)

It's possible step-by-step execution  in R-Studio? (i´m in server mode, not in local)

**Comment by asardaes** [comment]
Oh, then I'm not sure. Maybe it is possible but is all based on command line? In that case, you might have to type `n` and click Enter to execute a step.

**Comment by xtianfall** [comment]
I've left executing the first matrix (max time 3h) but the machine power off automaticly.
If tomorrow it doesn't save the result ill try with only 5k

**Comment by xtianfall** [comment]
OK, i've execute for nnn=10k and in both cases (`dist = "dtw" symmetric `= FALSE and `dist = "dtw_basic" symmetric = TRUE`) it works well and also with `maxabsdist=0`.

I've also execute the debug and it doesn't raise any error with nnn=10. I'm executing now with nnn=10k but i suppose that it will not raise any error.

**Comment by xtianfall** [comment]
For nnn=10k it breaks in
```
d <- foreach(pairs = pairs, .combine = c, .multicombine = TRUE, 
    .packages = control$packages, .export = export) %op% {
    if (!check_consistency(dist_entry$names[1L], "dist")) 
        do.call(proxy::pr_DB$set_entry, dist_entry)
    dd <- do.call(proxy::dist, enlist(x = x[pairs[, 1L]], y = x[pairs[, 
        2L]], method = distance, dots = dots))
    dd
}
Ill execute again later to double check ;)
```

**Comment by asardaes** [comment]
Just to be clear, it crashed with the following code:

```r
fam <- new("tsclustFamily", dist = "dtw", preproc=zscore, control = partitional_control(symmetric = TRUE))
debugonce(fam@dist)
matriz10kdtw=fam@dist(series, ...)
```

But it executed correctly for `symmetric = FALSE`?

**Comment by xtianfall** [comment]
That's correct.
I'll run later again to double check

**Comment by asardaes** [comment]
Bummer, I'll have to do some tests but can't do them right now. Could you run the following with a parallel backend? It shouldn't take too long.

```r
fam <- new("tsclustFamily", dist = "L1", control = partitional_control(symmetric = TRUE))
series <- dtwclust:::any2list(muestra[1:10000, 1:10])
matriz10k=fam@dist(series)
```

Notice that I'm also taking less columns from `series`. If that one doesn't fail, try taking all columns again and see if that one fails, i.e.:

```r
fam <- new("tsclustFamily", dist = "L1", control = partitional_control(symmetric = TRUE))
series <- dtwclust:::any2list(muestra[1:10000,])
matriz10k=fam@dist(series)
```

**Comment by xtianfall** [comment]
The first one is done whitout problem.
Executing the second one (with no debug)

**Comment by xtianfall** [comment]
And the second one ran without problem too.

Thats very weird...

**Comment by xtianfall** [comment]
I'll try in a minutes, but with nnn=1k (since with no parallel backend is very slow).

Do you mean that my matrix are wrong?

**Comment by asardaes** [comment]
You mentioned before that 1k works, so it would have to be a case that you know fails in parallel. If it's too time consuming to run 10k, I understand, but there's no point testing 1k.

I don't think it has to do with your matrices, I'm just saying that the problem may be in the `proxy` package, but I don't know how that one works internally so I can't say for sure.

I'll do some tests in the evening and let you know my thoughts afterwards.

**Comment by xtianfall** [comment]
I can execute for 10k tomorrow, but i dont knot if it will finish in 6h...

I mean, i've used prepoc because in the clusterings i've also use it. I need to compute the matrix in order to calculate the CVIs and since I use the same two distances for all the different test i precompute  them and then insert it in the tsclust object (i'm avoiding the calculation in the cvi command).

If the fam@dist doesn't have prepoc in account, i think that my matrices are wrong :S

**Comment by asardaes** [comment]
I'll add a note about that in the documentation, but no, `preproc` is not called there. It is called by `tsclust` or `predict`, for instance.

**Comment by asardaes** [comment]
Is there a way you can monitor RAM usage in the system that's running the calculations? The crash you're having does sound like running out of RAM (even if you have 140 GB of it). I don't think this is the case, but it could be.

I tried to reproduce this in my machine, and I couldn't complete either. RStudio didn't crash, but I did get some errors, and I did see RAM hitting the limit (I only have 16 GB).

I'm not sure if I can help you further. I will try to improve memory handling a little, but only for the distances I implemented in dtwclust. Doing parallelization and symmetric optimizations for other distances registered with proxy would be more difficult, and currently I actually don't know how to do it.

You might have to stick with `symmetric = FALSE`. For the distances included with dtwclust, you can call `proxy::dist` directly and still get parallelization, but you need to do it with two arguments to avoid symmetric optimizations, for example: `proxy::dist(series, series, method = "dtw_basic", ...)`. The `symmetric` parameter doesn't matter for the distances I implemented, I'll have to adjust documentation for that too (they detect it automatically).

**Comment by xtianfall** [comment]
I don't think so... I'll ask but I've no access to machine...

10k its a big dataset, altought i'll have to deal with bigger ones jajaj

You've help enought, I've done the matrixes and it works well. I don't know if some of those are limiting something, i think thats maybe is a parallel overflow o data mistake.

I dont know if i'll need to calculate more matrices, but i'll have in mind ;)

**Comment by asardaes** [comment]
Oh well, if you manage to check if RAM is the problem, let me know.

Thing is, based on the tests I made, I figured I (and also you) should be able to calculate the 10k x 10k matrix, even with only 16 GB of RAM in my case. Nevertheless, when the `foreach` parallel loop finished, it started collecting all the data from the parallel workers, and RAM usage increased far more than I would have expected, and I don't know why. Maybe `foreach` simply isn't made to serialize so much data.

I have an idea to improve this, but right now I'm not sure it's even possible. I'll have to see.

**Comment by asardaes** [comment]
Implementing my idea was made possible by the [bigmemory package](cran.r-project.org/package=bigmemory). If you can install from GitHub (see the [README](https://github.com/asardaes/dtwclust#installation)), you could try the modified functionality and see if it helps at all.

I still see a spike in RAM usage at the end, so maybe the problem is not `foreach`, but rather `proxy`. If you have a lot of time, you could try testing parallel and symmetric GAK, which internally uses `mapply` instead of `proxy::dist`. However, since everything worked when you used `L1` distance, really nothing is certain.

**Comment by xtianfall** [comment]
I'll try instaling the github version, but i think that it can not install devtools and r-tools since i'm in a R virtual machine, no with all system access. I'll ask anyway.

**Comment by asardaes** [comment]
Is it a Windows machine? You could probably download the [zip file from AppVeyor](https://ci.appveyor.com/project/asardaes/dtwclust/build/job/e7lg338c87ef0gcl/artifacts) and install it like other packages with:

```r
# path2file should be a character with the path to the zip file with respect to your working directory
install.packages(path2file, type="source", repos=NULL)
```

Those builds don't have a vignette though.

**Comment by xtianfall** [comment]
No, i think it's a Linux, it's an azure machine

**Comment by asardaes** [comment]
Then you should be able to install from GitHub without Rtools. Rtools is for Windows as far as I know.

**Comment by xtianfall** [comment]
I'll try when the machine finish with calculations...

I'm trying to determinate the number of clusters and with partitional and CVI's I don't get nothing consistent... I'm trying with hierachical to infer the cut ^^"

**Comment by xtianfall** [comment]
I've tried installing `devtools` and it doesn't work. In any case, the calculation of distmat work without errors now. Possibly i'll need to calculate for 100k or 1M in the future (it's no definitely, but possibly yes) and we'll see if the error persist big very big data.

```
 > install.packages('devtools')
 Installing package into ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4’
 (as ‘lib’ is unspecified)
 also installing the dependencies ‘curl’, ‘openssl’, ‘httr’, ‘git2r’
 
 trying URL 'https://cran.rstudio.com/src/contrib/curl_2.7.tar.gz'
 Content type 'application/x-gzip' length 406509 bytes (396 KB)
 ==================================================
 downloaded 396 KB
 
 trying URL 'https://cran.rstudio.com/src/contrib/openssl_0.9.6.tar.gz'
 Content type 'application/x-gzip' length 1239339 bytes (1.2 MB)
 ==================================================
 downloaded 1.2 MB
 
 trying URL 'https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz'
 Content type 'application/x-gzip' length 133398 bytes (130 KB)
 ==================================================
 downloaded 130 KB
 
 trying URL 'https://cran.rstudio.com/src/contrib/git2r_0.18.0.tar.gz'
 Content type 'application/x-gzip' length 1122935 bytes (1.1 MB)
 ==================================================
 downloaded 1.1 MB
 
 trying URL 'https://cran.rstudio.com/src/contrib/devtools_1.13.2.tar.gz'
 Content type 'application/x-gzip' length 486355 bytes (474 KB)
 ==================================================
 downloaded 474 KB
 
 * installing *source* package ‘curl’ ...
 ** package ‘curl’ successfully unpacked and MD5 sums checked
 Package libcurl was not found in the pkg-config search path.
 Perhaps you should add the directory containing `libcurl.pc'
 to the PKG_CONFIG_PATH environment variable
 No package 'libcurl' found
 Package libcurl was not found in the pkg-config search path.
 Perhaps you should add the directory containing `libcurl.pc'
 to the PKG_CONFIG_PATH environment variable
 No package 'libcurl' found
 Using PKG_CFLAGS=
 Using PKG_LIBS=-lcurl
 ------------------------- ANTICONF ERROR ---------------------------
 Configuration failed because libcurl was not found. Try installing:
  * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
  * rpm: libcurl-devel (Fedora, CentOS, RHEL)
  * csw: libcurl_dev (Solaris)
 If libcurl is already installed, check that 'pkg-config' is in your
 PATH and PKG_CONFIG_PATH contains a libcurl.pc file. If pkg-config
 is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
 R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
 --------------------------------------------------------------------
 ERROR: configuration failed for package ‘curl’
 * removing ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4/curl’
 Warning in install.packages :
   installation of package ‘curl’ had non-zero exit status
 * installing *source* package ‘openssl’ ...
 ** package ‘openssl’ successfully unpacked and MD5 sums checked
 Using PKG_CFLAGS=
 Using PKG_LIBS=-lssl -lcrypto
 ------------------------- ANTICONF ERROR ---------------------------
 Configuration failed because openssl was not found. Try installing:
  * deb: libssl-dev (Debian, Ubuntu, etc)
  * rpm: openssl-devel (Fedora, CentOS, RHEL)
  * csw: libssl_dev (Solaris)
  * brew: openssl@1.1 (Mac OSX)
 If openssl is already installed, check that 'pkg-config' is in your
 PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
 is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
 R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
 --------------------------------------------------------------------
 ERROR: configuration failed for package ‘openssl’
 * removing ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4/openssl’
 Warning in install.packages :
   installation of package ‘openssl’ had non-zero exit status
 * installing *source* package ‘git2r’ ...
 ** package ‘git2r’ successfully unpacked and MD5 sums checked
 checking build system type... x86_64-unknown-linux-gnu
 checking host system type... x86_64-unknown-linux-gnu
 checking for gcc... gcc
 checking whether the C compiler works... yes
 checking for C compiler default output file name... a.out
 checking for suffix of executables... 
 checking whether we are cross compiling... no
 checking for suffix of object files... o
 checking whether we are using the GNU C compiler... yes
 checking whether gcc accepts -g... yes
 checking for gcc option to accept ISO C89... none needed
 checking for library containing inflate... -lz
 checking for pkg-config... /usr/bin/pkg-config
 checking pkg-config is at least version 0.9.0... yes
 checking for libssl... no
 configure: WARNING: "pkg-config failed to find libssl."
 checking for library containing EVP_EncryptInit... no
 configure: error: in `/tmp/RtmptzbgST/R.INSTALL54d44989ffb9/git2r':
 configure: error: 
   ---------------------------------------------
    The OpenSSL library that is required to
    build git2r was not found.
 
    Please install:
      libssl-dev    (package on e.g. Debian and Ubuntu)
      openssl-devel (package on e.g. Fedora, CentOS and RHEL)
      openssl       (Homebrew package on OS X)
    and try again.
 
    If the OpenSSL library is installed on
    your system but the git2r configuration
    is unable to find it, you can specify
    the include and lib path to OpenSSL with:
    R CMD INSTALL --configure-args='--with-libssl-include=INCLUDE_PATH --with-libssl-lib=LIB_PATH' git2r
   ---------------------------------------------
 See `config.log' for more details
 ERROR: configuration failed for package ‘git2r’
 * removing ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4/git2r’
 Warning in install.packages :
   installation of package ‘git2r’ had non-zero exit status
 ERROR: dependencies ‘curl’, ‘openssl’ are not available for package ‘httr’
 * removing ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4/httr’
 Warning in install.packages :
   installation of package ‘httr’ had non-zero exit status
 ERROR: dependencies ‘httr’, ‘git2r’ are not available for package ‘devtools’
 * removing ‘/home/[...]/R/x86_64-pc-linux-gnu-library/3.4/devtools’
 Warning in install.packages :
   installation of package ‘devtools’ had non-zero exit status
 
 The downloaded source packages are in
 	‘/tmp/Rtmp1JcBv5/downloaded_packages’
```

**Comment by asardaes** [comment]
All right. If at some point you want to test it before it is on CRAN, I could provide a compiled package.

**Comment by xtianfall** [comment]
Ok, thank you ^^.
