### ISSUE TITLE
How to add legend onto the dtwclust plot?

### ISSUE THREAD

**Issue by sergiowang** [asardaes/dtwclust#2]
After using the patitional clustering, I can't tell which series belongs to which clust from the plot result. If there is a legend or a table that shows each cluster and its members' name, it would be much easier. But how could i add such a legend or a table?

**Comment by asardaes** [comment]
I'm not sure adding such a legend is possible right now. However, if you want to identify cluster membership you could look at the `cluster` slot of the returned object:

```r
data(uciCT)

kc <- dtwclust(CharTraj[1:10], k = 2,
               distance = "sbd", centroid = "pam",
               seed = 3247)

print(kc@cluster)
```

Would that help?

**Comment by sergiowang** [comment]
Thank you very much. 'print(kc@cluster)' does help me !
 I'm a beginner in R, so there would be lots of obstacles.Maybe i will ask for your help rather frequently.Is that OK for you?
Really appreciate your help!  (^_^)

**Comment by asardaes** [comment]
I can help you with problems related to the package, although if you have questions to R in general I think there are better places where you can find lots of information.
