### ISSUE TITLE
Difference in Silhouette results

### ISSUE THREAD

**Issue by usercluster** [asardaes/dtwclust#21]
Hi,
I have observed that I obtain different results for the average silhouette index when comparing the values obtained internally using cvi and "Sil" to the average value I get using the silhouette function and averaging the third column of the results. How is this possible?
I am performing a clustering using the Shape-based distance "SBD" and "shape_extraction" for the centroid.

**Comment by asardaes** [comment]
Can you provide a reproducible example? I'm not sure which silhouette function you're referring to.

**Comment by usercluster** [comment]
Sure, here it is!

`library(dtwclust)
library(cluster)

data(uciCT)
series <- reinterpolate(CharTraj, new.length = max(lengths(CharTraj)))
series <- series[1:20]
View(series)
pc.sb <- tsclust(series, k = 5L,
                 distance = "SBD", centroid = "shape",
                 seed = 3247, trace = TRUE,
                 control = partitional_control(nrep = 10L))
internal_Sil<-sapply(pc.l2, cvi, type="Sil")

d<-pc.sb[[1]]@family@dist(series)
silhouette_computed<-function(i){
 return(mean(silhouette(i@cluster,d)[,3]))
}
computed_Sil<-sapply(pc.sb,silhouette_computed)

computed_Sil==internal_Sil`

**Comment by asardaes** [comment]
A couple of remarks. Specifying `centroid = "shape"` means that `zscore` preprocessing will be used, so you should apply it to `series` before passing it to `family@dist`. Furthermore, the documentation for the `silhouette` function specifies that the `sil_width` of an observation will be 0 if the cluster is a singleton, and that is something `cvi` doesn't do ([Arbelaitz et al.](https://pdfs.semanticscholar.org/a522/fb4646ad19fe88893b90e6fbc1faa1470976.pdf) didn't mention that).

Even with that in mind, I'm still seeing discrepancies, but I'm not sure why, I'll have to look at the source code for `silhouette`.

**Comment by asardaes** [comment]
Never mind, I found the problem. The formula in Arbelaitz et al. isn't really correct, the average dissimilarity is not computed considering the size of the cluster, but rather the size minus 1 to account for the i-th series being considered. I guess I will change the code so that it simply calls the `silhouette` function from the cluster package.
