### ISSUE TITLE
Clustering series with NA

### ISSUE THREAD

**Issue by paco-ceam** [asardaes/dtwclust#22]
Hi and thanks for building such a useful package.
I'd like to know how to deal with series containing NA values. I have a bunch of daily temperatures (one value a day) but as they have intervals with NA values I could not use tsclust for the complete series, needed to join all the series in a common time interval. 
Can dtwclust deal with time series with gaps? Do the series need to be complete with data in every day?
Thanks again,
Paco

**Comment by asardaes** [comment]
Hi, `dtwclust` has no included functionality to deal with missing values, you have to take care of that beforehand. For that, you might want to look into time-series imputation, which is a whole research area of its own. See for example [this](https://journal.r-project.org/archive/2017/RJ-2017-009/RJ-2017-009.pdf).

**Comment by paco-ceam** [comment]
Hi Alexis and thanks. I will read the doc about imputation. Thanks
