### ISSUE TITLE
Zero-size clusters and clusinfo$size

### ISSUE THREAD

**Issue by slavickk** [asardaes/dtwclust#23]
Sometimes the timeseries get split into less number of clusters than requested, which causes zeros in clusinfo$size. This is expected, however when it's the last cluster that is empty then the clusinfo$size vector is shorter than the number of clusters due to how the tabulate() function works (I believe it is missing the nbin argument).

E.g. for 3 clusters:
```
> k <- 3
> tabulate(c(1,1, 2,2, 3,3))
[1] 2 2 2
> tabulate(c(1,1, 2,2))
[1] 2 2 # but we need 2 2 0
> tabulate(c(1,1, 2,2), nbin = k)
[1] 2 2 0 # this is desired
```
My understanding is that the following line is used to calculate the clusinfo$size vector and it is this line that needs to be fixed:
https://github.com/cran/dtwclust/blob/c9c03ba5da463ebe14d03d46bb21bfb0f1b41181/R/partitional-fuzzy.R#L128

**Comment by asardaes** [comment]
Sounds good, I'll fix it.
