### ISSUE TITLE
issues with zoo data frames

### ISSUE THREAD

**Issue by stemineo** [asardaes/dtwclust#24]
Hi, I am exploring/testing dtwclust for financial time series clustering analysis purpose.
I find it very effective but I am missing something about how it works.

I am using a multivariate dataset, which I have properly cleaned and preprocessed before using it as an input. In particular, I have:

- replaced +/-Inf with NAs

- interpolate the NAs between two entries (start-end valid values before and after NAs)

- replace the remaining NAs, which are not between two valid values, with zeros

The dataset consists on a list of 71 zoo data frames, each having 67 rows (time dimension, in quarters, equal for all 71 objects) and 13 columns (my variables, also equal for all 71 objects). Since the variables vary substantially, I do apply z-normalization to the dataset before using it as input to dtwclust.
My aim is to test the results of different algorithms, using different distance measures, clustering methods and centroid calculations. Here I show only the case study for GAK distances.
Below are my tests, examples, the errors I get and the questions I have for you.

#####
1) distance = "gak", type = "hierarchical"
`mvc_gak_h <- tsclust(mydata, k = 4L, type = "hierarchical", distance = "gak", seed = 390, args = tsclust_args(dist = list(sigma = 100)))`
In this case I have no problems at all, and can easily plot the results in a dendrogram.

#####
2) distance = "gak", type = "partitional", centroid = "pam"
```
mvc_gak_p_pam <- tsclust(mydata, k = 4L, type = "partitional", distance = "gak", seed = 392, centroid = "pam", args = tsclust_args(dist = list(sigma = 100)))
plot(mvc_gak_p_pam)
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
In this case I get an error when I try to plot the clustering results and I don't understand the error message. The clustering algorithm seem to work well. When I type `mvc_gak_p_pam` I obtain the following output:
```
partitional clustering with 4 clusters
Using gak distance
Using pam centroids
Time required for analysis:
   user  system elapsed 
   2.62    0.00    2.64 
Cluster sizes with average intra-cluster distance:
  size    av_dist
1   29 0.06585621
2   14 0.07254417
3   15 0.07099164
4   13 0.07744559
```

#####
3) distance = "gak", type = "partitional", centroid = "dba"
```
 mvc_gak_p_dba <- tsclust(mydata, k = 4L, type = "partitional", distance = "gak", seed = 394, centroid = "dba", args = tsclust_args(dist = list(sigma = 100)))
plot(mvc_gak_p_dba)
Error in vector(type, length) : 
  vector: cannot make a vector of mode 'NULL'.
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```
Similarly to the previous case, I get an error when I try to plot the clustering results, and I don't understand the error message. Where is the error exactly? The clustering algorithm seem to work well. When I type ` mvc_gak_p_dba` I obtain the following output:
```
partitional clustering with 4 clusters
Using gak distance
Using dba centroids
Time required for analysis:
   user  system elapsed 
   5.29    0.00    5.46 
Cluster sizes with average intra-cluster distance:
  size    av_dist
1   20 0.06968869
2    6 0.07500183
3   27 0.06434661
4   18 0.05622174
```

#####
4) distance = "gak", type = "partitional", centroid = "shape"
```
mvc_gak_p_shape <- tsclust(mydata, k = 4L, type = "partitional", distance = "gak", seed = 396, centroid = "shape", args = tsclust_args(dist = list(sigma = 100)))
Error in { : task 1 failed - "task 1 failed - "indexes overlap""
```
In this case I can't even run the clustering algorithm, and I do not understand the error message.

Finally, I use the option `args = tsclust_args(dist = list(sigma = 100))` just because I have seen it in the example for "Multivariate time series" in the dtwclust documentation (pag. 46), but I don't quite understand what it means and I didn't find any clear explanations neither in online forums, nor in the documentation. I only notices that the "av_dist" between clusters changes if I use or not use this option but I don't see why. Would you please help me clarifying these issues? Is there a better documented manual or website to consult?

Thanks,
Stefano

**Comment by asardaes** [comment]
Hello. That does sound weird, perhaps there is an issue with `zoo` data frames? I haven't personally tested them. Could you try changing them to matrices and see if you get the same error? Something like `mydata <- lapply(mydata, as.matrix)`.

The `sigma` parameter is described in the documentation for the `GAK` function. You can read more details about it in [Cuturi's paper](https://i.imgur.com/sp4uSJb.gifv) (around Table 2).

**Comment by stemineo** [comment]
After I converted the dataset into a matrix all the errors magically disappeared. Thanks.
(although this is also weird).

As for the paper: the link you above brings me here:
https://imgur.com/sp4uSJb

It is a sweet GIF, I do like puppies, but I'd be grateful to you if you could link me also Cuturi's paper.
Thanks :)

**Comment by asardaes** [comment]
Ha! Now people will know I like puppies. I've updated the link.

I will look into interaction with `zoo` data frames, but probably not soon.

**Comment by stemineo** [comment]
I have gone through the paper and I still don't understand the need of sigma. I mean, I do appreciate that it belongs to the definition of Gaussian kernel, which must be the only GAK type of kernel used in the function (is that right?). Why does one need to constrain sigma? And why it is specified using a list in the example. Why is the value 100 used?

**Comment by asardaes** [comment]
100 is just an example I used, it has no particular explanation.

It is passed in a list to `tsclust` because internally I use the `do.call` function a lot, and it takes a list of arguments as input.

Have you seen the code example in the documentation for `GAK`? As far as I understand, the kernel must be parameterized based on the data, and Cuturi proposed a way to estimate it stochastically. The example shows how to obtain one estimate, which you could apply to your data. You could also use several random seeds and see how the estimate is distributed.

I will also mention that the paper is indeed somewhat vague in its description of the estimation procedure, and I do not know enough about the theoretical foundation to attest its robustness.
