### ISSUE TITLE
Follow-up on adding legends to DTWClust plots

### ISSUE THREAD

**Issue by cperk** [asardaes/dtwclust#25]
How can I retain the name of each of my time series in the plots and dendrograms produced by DTWClust? So far I have found the package very useful but have to keep going back and forth between the order in @cluster and my data set to identify cluster membership. Also, the dendrograms produced in hierarchical clustering do not retain the unique names of my 24 time series, and instead label them 1-24. I know that two years ago there was no mechanism to do this (https://github.com/asardaes/dtwclust/issues/2) but wanted to check and see if a new feature has been added. Thank you!

**Comment by asardaes** [comment]
I think that if the input series have names, a dendrogram will also show them, so try assigning names to your series before clustering them (with `names<-`). The other plots haven't been changed, so they don't have legends by default. Something like [this](https://stackoverflow.com/a/45631834/5793905) seems like it should work (remember you get the ggplot object if you do something like `gg_object <- plot(cluster_object, plot = FALSE)`. I'll see if I can add it but I can't personally test it right now.

**Comment by asardaes** [comment]
Here's a *very* crude working example, I think I can later add something nicer to the plot method.

```r
library(dtwclust)
library(ggrepel)

series <- CharTraj[1:10]
pc <- tsclust(series)

df_labels <- lapply(pc@datalist, function(s) {
    # return
    data.frame(x = length(s) / 2L, y = s[length(s) / 2L])
})
df_labels <- do.call(rbind, df_labels)
df_labels$label <- names(series)
df_labels$cl <- pc@cluster

gg_obj <- plot(pc, plot=F)
gg_obj + geom_label_repel(aes(x=x, y=y, label=label), 
                          data=df_labels, 
                          nudge_x=10)
```

**Comment by cperk** [comment]
Thank you so much!! Just to clarify, the 2L corresponds to the number of
clusters I select in the tsclust command (in this case 2 clusters)?

**Comment by asardaes** [comment]
No, in this case that's for the location of the labels, so the x coordinate is half the length of the series, and the y coordinate is the corresponding series value.

**Comment by cperk** [comment]
Thank you so much! It worked very well!

**Comment by asardaes** [comment]
I've added a routine to the default plot method for `TSClusters`, I'll probably submit the new version of the package to CRAN at the beginning of February. Until then, feel free to try the github version of the package.

**Comment by cperk** [comment]
Excellent, thank you.

I had one more question: after running Kshape hierarchical clustering and
generating prototypes as you demonstrate in the vignette, is there a way to
use those prototypes as the centroids for clustering additional data?

**Comment by asardaes** [comment]
See #3 and the very last example in the PDF vignette, as well as the documentation for `predict` for `TSClusters`.

**Comment by cperk** [comment]
Oh yes, thank you. One more thing: how can I interpret the Y axis when I
plot the clusters from kshape hierarchical clustering in (type="sc")? Is it
the znormalized data on the Y axis or is it a measure of dissimilarity?
Does this differ for the Y axis on the dendrogram?

**Comment by asardaes** [comment]
One can induce a certain number of clusters by cutting the dendrogram, that plot shows the resulting groups of time series. See the documentation for `cutree` in R.

k-Shape is a partitional clustering algorithm. If you used hierarchical clustering with SBD, it is not actually k-Shape, so the series are not normalized by default in that case.
