### ISSUE TITLE
Question about number of clusters generated by hierarchical clustering

### ISSUE THREAD

**Issue by cperk** [asardaes/dtwclust#26]
In the dtwclust package, does hierarchical clustering automatically create 2 clusters if k is not specified?

**Comment by asardaes** [comment]
yes

**Comment by cperk** [comment]
Ok thanks! Is there a way to let it choose the optimum number of clusters
or do I need to specify a range of k values and evaluate them as in
partitional clustering?

**Comment by asardaes** [comment]
There's no automatic way, you can do it graphically (`identify.hclust`) or numerically (`cutree`). There might be other methods but I'm not aware of any.
