### ISSUE TITLE
install issue on windows

### ISSUE THREAD

**Issue by Jammcgro123** [asardaes/dtwclust#32]
Hi there, 

- I am trying to install DTWCLUST on R version 3.5.0. IT seems to install ok to begin with using the command : "

C:\Program Files\R\R-3.5.0\bin\Rscript" -e "install.packages('dtwclust',repos='http://cran.r-project.org',dependencies=TRUE)"

- I receive the output: 

"trying URL 'http://cran.r-project.org/bin/windows/contrib/3.5/dtwclust_5.4.0.zip'
Content type 'application/zip' length 3723853 bytes (3.6 MB)
==================================================
downloaded 3.6 MB

package 'dtwclust' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Administrator.QUB\AppData\Local\Temp\RtmpOeAlKI\downloaded_packages"

- when i try to add the package while in R 3.5.0 i receive the following issue:

"> library("dtwclust")
Loading required package: proxy

Attaching package: ‘proxy’

The following objects are masked from ‘package:stats’:

    as.dist, dist

The following object is masked from ‘package:base’:

    as.matrix

Loading required package: dtw
Loaded dtw v1.18-1. See ?dtw for help, citation("dtw") for use in publication.

Error: package or namespace load failed for ‘dtwclust’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’"

- Is there a resolution for this?

**Comment by asardaes** [comment]
Well you could try manually installing `stringi`, since it tells you it's missing. I don't know why it wasn't installed with the other dependencies, but that sometimes seems to happen (a specific dependency not installing automatically).
