### ISSUE TITLE
I want to compare the cluster algorithm, but it has an error because ncol too large.

### ISSUE THREAD

**Issue by duangrux** [asardaes/dtwclust#36]
I want to compare the clustering algorithm, but it has an error because ncol too large.
my dataset has 155 column and 1900 observations.
and I also have another dataset that has 300 column and 1900 observations.

how should  i do?
```
> sapply(list(HC=hc, DTW = pc_dtw, kShape = pc_sbd, FuzzyM = fcm),
+        cvi, b = lst_label, type = "VI") #Internal, Minimize
Error in matrix(0L, nrow(a), max(b)) : 
  invalid 'ncol' value (too large or NA)
In addition: There were 50 or more warnings (use warnings() to see the first 50)
```

**Comment by asardaes** [comment]
What's the format of `lst_label`? For specific issues, it really helps to have a [reproducible example](https://stackoverflow.com/a/5963610/5793905).
