### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by fgomeza17** [asardaes/dtwclust#40]
hi... i have a problems with the installation when I try to use "install.packages("dtwclust")"...
this is the output message and I can't find a solution:

the version of R was updated for 3.5.2 and try it again

> install.packages("dtwclust")
probando la URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.5/dtwclust_5.5.1.tgz'
Content type 'application/x-gzip' length 4141751 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/vg/8jx_2g9s1v3fz5w2x10y_qkh0000gn/T//Rtmpyr24Ub/downloaded_packages

**Comment by asardaes** [comment]
Google says you should try [this](https://stackoverflow.com/a/3909546/5793905).
