### ISSUE TITLE
bug in timestamp consistency

### ISSUE THREAD

**Issue by cat630** [asardaes/dtwclust#47]
If I provide a param time in  plot (~,time=100), it always returns "  Length mismatch between values and timestamps").

here is the source code.
 # timestamp consistency
    if (!is.null(time) && length(time) < max(L1, L2))
        stop("Length mismatch between values and timestamps") # nocov

**Comment by asardaes** [comment]
You need to provide a vector, not a single value. There is an example in the documentation of `tsclust`:

```r
require(scales)
t <- seq(Sys.Date(), len = length(series[[1L]]), by = "day")
gpc <- plot(pc.tadp, time = t, plot = FALSE)

gpc + ggplot2::scale_x_date(labels = date_format("%b-%Y"),
                            breaks = date_breaks("2 months"))
```
