### ISSUE TITLE
sigma error

### ISSUE THREAD

**Issue by jesuslovesyiyi** [asardaes/dtwclust#48]
when running the tsclust function on a multivariate model with varying time series length, I run into the error: Parameter 'sigma' must be positive. Do you have any idea what could be the issue? Thanks in advance!

**Comment by asardaes** [comment]
Are you using the GAK distance?

**Comment by jesuslovesyiyi** [comment]
> Are you using the GAK distance?

Yes

**Comment by asardaes** [comment]
If you specify `sigma` for that distance, it must be positive. I don't think the automatic estimate can give a negative result.
