### ISSUE TITLE
Does dtw_basic do open-ended alignments by default?

### ISSUE THREAD

**Issue by masonyoungblood** [asardaes/dtwclust#51]
I'm using dtw_basic with proxy::dist, and after hierarchical clustering (with a variety of different parameter combinations) I'm getting clusters where very short signals are getting matched with very long signals that have a similar sub-sequence. It seems as though dtw_basic might be doing open-ended alignment. Is that the case? I can't find anything about it in the documentation.

I'm using a window size of 5-10% (of the average signal length), so I'm not sure how else these signals would be clustered together. Let me know if you have any thoughts!

**Comment by asardaes** [comment]
Hello, no, the `dtw_basic` version doesn't do open-end alignments. Are you setting `normalize = TRUE`?

**Comment by masonyoungblood** [comment]
Okay thanks, and yeah I'm using normalize - Could that be inflating the
similarity between signals of different lengths?

**Comment by asardaes** [comment]
No, it's the other way around, that's why I wanted to know. It could also be that the distance between those long/short series is high, but there's just no other centroid with more similarity.
