### ISSUE TITLE
dtwclust command not find

### ISSUE THREAD

**Issue by 0310-mich** [asardaes/dtwclust#53]
Hi there, 

I have been trying to use the "dtwclust" package but keep getting the error that RStudio can't find the function dtwclust despite I have all the last R, method, proxy, and dtw updates. 
![image](https://user-images.githubusercontent.com/62868869/111881821-957b4580-89b2-11eb-8e85-3f49656786e0.png)

Thanks

**Comment by asardaes** [comment]
Hello, are you sure the package is loaded with `library(dtwclust)`?

**Comment by 0310-mich** [comment]
Hi asardaes, 
Yes I am

**Comment by 0310-mich** [comment]
Hey there, 

Yah I also did that, I also re-install R-Studio and every recommended package but nothing change, it still doesn't recognize it.
![image](https://user-images.githubusercontent.com/62868869/112445005-f312e780-8d4e-11eb-8f13-11b810cbd1b7.png)
Despite that some other functions of your wonderful package work, that one is inexistant. Is it working on your computer? 

Thanks, 

Guillaume

**Comment by asardaes** [comment]
Strange, what do you see if you run the following?

```
library(dtwclust) 
sessionInfo()
```

Also, do you see the function with 3 colons? I.e. `dtwclust:::`

**Comment by asardaes** [comment]
Well this is embarrassing. Sorry, I haven't worked with R for a while now. The `dtwclust` *package* doesn't have a `dtwclust` *function*, that's been gone for a long time now, the main function is `tsclust`.

**Comment by 0310-mich** [comment]
Yes, I am, but thanks a lot already man! 
Your package will still be really helpful in my studies!

**Comment by asardaes** [comment]
No problem :+1:
