### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Be4UChoose2Exit** [asardaes/dtwclust#60]
Hi When I install dtwclust on rweb services, I am getting this error:
(sorry for the image because I am not allowed to copy the codes from this environment)

<img width="651" alt="屏幕截图 2022-06-14 103353" src="https://user-images.githubusercontent.com/26829002/173482175-f6e958ab-9b9f-47e9-beb9-9f5745554d84.png">
<img width="652" alt="屏幕截图 2022-06-14 103447" src="https://user-images.githubusercontent.com/26829002/173482199-0b2f76e8-7ec5-404e-878a-13f2d5511f53.png">
I am using **gcc version of 8.3** and down below is my environment info:
<img width="258" alt="屏幕截图 2022-06-14 103902" src="https://user-images.githubusercontent.com/26829002/173482248-8068a5f0-20f5-4c57-8d35-036f8c3903f2.png">

Thanks!

**Comment by asardaes** [comment]
Hello, the error points to `RcppThread`, so you might have to update that package first?

**Comment by Be4UChoose2Exit** [comment]
> Hello, the error points to `RcppThread`, so you might have to update that package first?

I just upgraded `RcppTHread` to 2.1.3 which is the latest; however I am still getting the same error.

**Comment by asardaes** [comment]
I see you already asked in tnagler/RcppThread#65. I also suspect the toolchain in your env is too old, but I'm not sure how to check. What distro do you have?
