### ISSUE TITLE
Confusing documentation for minimized CVIs

### ISSUE THREAD

**Issue by mymil** [asardaes/dtwclust#61]
I wrote up a whole issue with a reprex about not being able to reproduce the majority voting outcome from `cvi_evaluators()` and `compare_clusters()`, but just noticed that there's a sentence in Details of the `cv_evaluators()` help that says the output of CVIs are inverted for those where smaller is better.

I was primarily referring to the summaries of the CVIs in the help for `cvi()` while working, so I missed that note entirely. It would be helpful if that point were emphasize more strongly, or perhaps a message printed accompanying results. Getting inverted output is surprising behavior, in my opinion.

Thank you for all your work on this package! It has been otherwise very easy to use.

**Comment by asardaes** [comment]
Sure, I can add a message when calling `cvi_evaluators`, that way it will only be shown once for a given call.

**Comment by mymil** [comment]
Thank you!
