### ISSUE TITLE
Partitionial clustering, which method?

### ISSUE THREAD

**Issue by ElliotPS1992** [asardaes/dtwclust#64]
Hello, 

I am clustering a big longitudinal dataset with around 100,000 subjects. In another issue for someone else you suggested to use partitional clustering with not the PAM centroid for large datasets. This works really well and fast with for example dba or sdtw. However, I was wondering what kind of partitional clustering is used in case of dba or sdtw. For instance, K-means, K-mediods or something else?

Thank you in advance. 

Kind regards, Leslie

**Comment by asardaes** [comment]
Hi, I'm not sure I get the question, DBA is a centroid algorithm that can be used with k-means, only using PAM counts as k-medoids.
