### ISSUE TITLE
What do the colors and vertical lines mean in plot.TSClusters?

### ISSUE THREAD

**Issue by maellecoursonnais** [asardaes/dtwclust#66]
Hello,

I could not find anything in the documentation about the different colors used in the plots, and the vertical lines. Do they bear some meaningful information? Can you point me to some documentation, or maybe directly answer here?

Here is some reproducible data:
```r
library(dtwclust)
data("uciCT")

mvc <- tsclust(CharTrajMV, k = 4L, distance = "gak", seed = 390L)
plot(mvc, type = "series")
```
![image](https://github.com/asardaes/dtwclust/assets/64737131/258fc7b8-3b7f-4081-b1c2-e64f0327fcfd)

**Comment by asardaes** [comment]
The colors are just random to try to make it easier to differentiate between series. The vertical lines separate each variable from a multivariate series.
