### ISSUE TITLE
How to plot univariate trajectories from multivariate clustering?

### ISSUE THREAD

**Issue by maellecoursonnais** [asardaes/dtwclust#67]
Hello,

I carry a multivariate time series clustering, and your package makes it very easy to do so. However, I'd like to plot the univariate time series (i.e., the different columns) separately with `plot.TSClusters`. I could not find anything in the documentation of the function about this.

Here's a reproducible example:
```r
library(dtwclust)
data("uciCT")

mvc <- tsclust(CharTrajMV, k = 4L, distance = "gak", seed = 390L)
plot(mvc, type = "series")
```
![image](https://github.com/asardaes/dtwclust/assets/64737131/17dfb609-d32c-4ea7-ab00-a21fec316dad)

From what I understand, the time series cluster plot are somewhat summarizing the multivariate time series, but I'd like to separate them out.

Cheers

**Comment by asardaes** [comment]
You can't do that with the included method, it is only meant as a generic plot to handle the most common scenarios, if you need anything more sophisticated you're probably better off implementing your own logic, maybe the source code can serve as reference:

https://github.com/asardaes/dtwclust/blob/5f9f16856629dda615a3b19efc91e705c7ef1393/R/S4-TSClusters-methods.R#L582
