### ISSUE TITLE
Is it possible to perform compare_clusterings using pre-calculated DTW distances?

### ISSUE THREAD

**Issue by FraniaKlaisinga** [asardaes/dtwclust#68]
Hello,

I could not find anything in the documentation about using previously calculated distances with proxy::dist. The idea behind this is to leverage the time invested in that work.

**Comment by asardaes** [comment]
If I recall correctly, `compare_clusterings` should also use a distance matrix provided in the `distmat` parameter from [tsclust-controls] (https://rdrr.io/cran/dtwclust/man/tsclust-controls.html), but keep in mind the limitations mentioned in that docu.
