### ISSUE TITLE
How many clusters: easily compute indices of "fit" (e.g., silhouette score)

### ISSUE THREAD

**Issue by DominiqueMakowski** [asardaes/dtwclust#69]
Thanks for the package. I was wondering if there was a way of easily estimating the optimal numbers of clusters by computing some indices of fit, e.g., the Silhouette score. 

I checked the documentation of `compare_clusterings()` but it seems like an overkill as compared to what I would like to get.

Any pointers appreciated :)

**Comment by asardaes** [comment]
[`cvi`](https://rdrr.io/cran/dtwclust/man/cvi.html)?

**Comment by DominiqueMakowski** [comment]
Yes indeed, I missed it and it's exactly what I needed. Cheers!
