### ISSUE TITLE
segfault error using dtwclust

### ISSUE THREAD

**Issue by hichew22** [asardaes/dtwclust#71]
I am trying to use dtwclust as follows. I have a large dataframe consisting of longitudinal Y values (1 value per day, 31 values per individual, and ~700 individuals). There are no missing values.

```
df_ts <- tsmatrix(df, response = "Y")
dtwclust::tsclust(
  df_ts,
  k = 4L
)
```

This code chunk works when I am directly calling it, but when I try to knit, the following segfault error occurs:

![image](https://github.com/asardaes/dtwclust/assets/137368713/b32b56c7-0f71-4675-91f2-5679c160dc68)

Could you help me with this?

**Comment by asardaes** [comment]
hm, the top-most call seems to be done by `RcppParallel`, so it's likely related to that. Did you customize its installation in any way?

**Comment by asardaes** [comment]
Not sure, I actually don't know if `RcppParallel` still dynamically compiles its backend or not. What CPU do you have?

**Comment by asardaes** [comment]
Ah I missed the part about knitting, then I don't know if the traceback is super accurate, a quick search returned [this](https://stackoverflow.com/questions/76636654/invalid-permissions-in-vs-code-running-quarto-file-with-r-code), although that's a bit old, but maybe your setup suffers from something similar?

**Comment by asardaes** [comment]
I imagine [this](https://stackoverflow.com/a/52262190/5793905) would work (note the comment from Jaleks).

However, if reading the env var was the problem, I think the call to `defaultNumThreads` wouldn't appear in the traceback, so I still think it would be interesting to know which CPU you have.

**Comment by asardaes** [comment]
Could you post the basic config of the document you're trying to knit? And you're knitting from rstudio?

There seems to be a lot of examples of segfaults when I search for R and apple silicon, so it might be tricky, but I can at least try to reproduce. Maybe check [this comment](https://github.com/rstudio/rstudio/issues/12280#issuecomment-1972540221).

**Comment by asardaes** [comment]
I rather meant the metadata from the document, things like these:

```
---
title: "blah"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using table.express}
  %\VignetteEngine{knitr::rmarkdown_notangle}
  %\VignetteEncoding{UTF-8}
---
```

Also, from what I can tell, `kmlShape` was archived in CRAN, and its [last status](https://cran-archive.r-project.org/web/checks/2022/2022-12-19_check_results_kmlShape.html) shows the comiled code had some significant warnings, so that could be an issue out of my control. The [`kml` package from the same authors](https://cran.r-project.org/package=kml) seems to be updated, does that one provide the same functionality you're currently using?
