### ISSUE TITLE
De-normalizing after zscore preprocessing

### ISSUE THREAD

**Issue by zdegreve** [asardaes/dtwclust#8]
Hello,

Is there a simple way with dtwclust to get the means and standard deviations used by zscore during preprocessing, in order to perform denomalization ? 

Thank you in advance.

Regards,

Zacharie

**Comment by asardaes** [comment]
Not really, but what do you need it for? You could substitute the `@datalist` slot with the original data if you wanted, but if you want that info for de-normalizing the obtained centroids or something similar, you're gonna have to do the normalization yourself. The `zscore` function is just a wrapper for `scale`, and if you use the latter directly, it will return the mean and standard deviation as an attribute of the result.

**Comment by zdegreve** [comment]
OK thank you, I would like to descale the centroids indeed. I will use the scale command therefore.

Thanks !

--
------------------------------------------------------------------------------
Zacharie De Grève - PhD
Research and Teaching Assistant - Power Electrical Engineering Department
University of Mons -  Faculty of Engineering
Bd Dolez, 31 BE-7000 Mons
Tél : +32 (0)65 374117
Fax : +32 (0)65 374120
https://sites.google.com/site/zachariedegreve/
------------------------------------------------------------------------------
________________________________
De : Alexis Sarda [notifications@github.com]
Envoyé : mercredi 28 septembre 2016 14:56
À : asardaes/dtwclust
Cc : Zacharie DE GREVE; Author
Objet : Re: [asardaes/dtwclust] De-normalizing after zscore preprocessing (#8)


Not really, but what do you need it for? You could substitute the @datalist slot with the original data if you wanted, but if you want that info for de-normalizing the obtained centroids or something similar, you're gonna have to do the normalization yourself. The zscore function is just a wrapper for scale, and if you use the latter directly, it will return the mean and standard deviation as an attribute of the result.
