### ISSUE TITLE
Incompatibility with saved object from previous version

### ISSUE THREAD

**Issue by sergiowang** [asardaes/dtwclust#9]
Hi Alexis.
I have my `dtwclust-class` objects produced under one previous release of package dtwclust. After I update the package to the lastest version, the `predict(previous_object,series)` doesn't work. 
So I downloaded the previous release zip and try to install it. 
However, when I use `install.packages("d:/dtwclust-2.2.1.zip", repos = NULL, type = "source")`, no error comes out but the package is not successfully installed beacause it can't be found in my package list.
It would be difficult to reproduce my `dtwclust-class` objects in the latest version because it's extreme complicating.
Is there any other solution to get the previous package successfully installed?

**Comment by asardaes** [comment]
Hi Sergio, please try the following after loading your previous object:

```r
previous_object@centroids <- previous_object@centers
```

Then check if `predict` works. Let me know.

**Comment by sergiowang** [comment]
Unluckily, It doesn't work and returns: `Error in object@family@preproc(newdata, ... = object@dots) : 
  unused argument (... = object@dots)`.

**Comment by asardaes** [comment]
Oh ok, then in addition to the previous, also do this:

```r
previous_object@family@preproc <- edit(previous_object@family@preproc)
```

On the window that appears, add a `, ... ` to the function arguments, then try again. 

I'm sorry, I didn't consider the possibility of people having objects saved, so I didn't include specific instructions on how to "update" them. Let me know if that helps.

**Comment by sergiowang** [comment]
It works. Thank you again for your instruction. :-)
